### ISSUE TITLE
can't launch scan - java exception

### ISSUE THREAD

**Issue by itbelongsinamuseum** [quentinhardy/jndiat#2]
Hello,

I can display the help or the version but I get some errors when trying the scan command as shown below (I hidded the IP):

```
java -jar Jndiat_v1.0.jar scan -s X.X.X.X --ports 7001                                                                                                                                                                      

[1] Scanning port(s) with the T3 protocol
Exception in thread "main" java.lang.NoClassDefFoundError: org/omg/CORBA_2_3/portable/ObjectImpl
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at weblogic.jndi.WLSJNDIEnvironmentImpl.<clinit>(WLSJNDIEnvironmentImpl.java:63)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at weblogic.jndi.internal.JNDIEnvironment.getJNDIEnvironment(JNDIEnvironment.java:33)
        at weblogic.jndi.Environment.<clinit>(Environment.java:89)
        at weblogic.jndi.WLInitialContextFactory.getInitialContext(WLInitialContextFactory.java:117)
        at java.naming/javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:730)
        at java.naming/javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
        at java.naming/javax.naming.InitialContext.init(InitialContext.java:236)
        at java.naming/javax.naming.InitialContext.<init>(InitialContext.java:208)
        at T3Connection.connection(Unknown Source)
        at Scanner.scan(Unknown Source)
        at Jndiat.<init>(Unknown Source)
        at Jndiat.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.omg.CORBA_2_3.portable.ObjectImpl
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 23 more
```

the version of JndiAT I used:
```
java -jar Jndiat_v1.0.jar --version                                                                                                                                                                                                
JndiAT version 1.0 (built: 2021/09/13)
```

And the version of Java:
```
openjdk 11.0.12 2021-07-20
OpenJDK Runtime Environment (build 11.0.12+7-post-Debian-2)
OpenJDK 64-Bit Server VM (build 11.0.12+7-post-Debian-2, mixed mode, sharing
```

Are you aware of this bug ?

Thank you,

**Comment by Anas-jaf** [comment]
use  openjdk-8
